#!/bin/bash
clear
#colors
WHITE="\033[1;37m"                                          ##
grey="\033[0;37m"                                           ##
purple="\033[1;35m"                                         ##
RED="\033[1;31m"                                            ##
green="\033[1;32m"                                          ##
yellow="\033[1;33m"                                         ##
purple="\033[0;35m"                                         ##
cyan="\033[0;36m"                                           ##
CYAN="\033[1;36m"                                          ##
cafe="\033[0;33m"                                           ##
fiuscha="\033[0;35m"                                        ##
blue="\033[1;34m"                                           ##
l_red="\033[1;37;41m"                                       ##
nc="\033[0m"                                                ## 
pink="\e[95m"  
msg() { 
printf "${green}[${nc}+${green}] ${white}${1}\n${nc}"
 }
errormsg () {
printf "${red}[!] ${white}${1}\n${nc}"
}
function check_root() {
        if [ "$(whoami &2>/dev/null)" != "root" ] && [ "$(id -un &2>/dev/null)" != "root" ];then
                echo ""
                echo ""
                errormsg "Admin user detected\n"
                errormsg "Use 'sudo !!'\n"
                exit 1
	fi
}
function os () {
cat /etc/os-release &> /dev/null 2>&1
	if [ "$?" -eq "0" ]; then
		OS=DEBIAN 
		BIN="/usr/bin"
		file="/usr/share/HCO-Phish"
		check_root
	else
		OS=TERMUX
		file="$PREFIX/share/HCO-Phish"
		BIN="$PREFIX/bin"
	fi
}
banner() {
	printf "${green}

          ▒█░▒█ ░ ▒█▀▀█ ░ ▒█▀▀▀█ 
          ▒█▀▀█ ▄ ▒█░░░ ▄ ▒█░░▒█ 
          ▒█░▒█ █ ▒█▄▄█ █ ▒█▄▄▄█ 

   ▒█▀▀█ ▒█░▒█ ▀█▀ ▒█▀▀▀█ ▒█░▒█ ▒█▀▀▀ ▒█▀▀█ 
   ▒█▄▄█ ▒█▀▀█ ▒█░ ░▀▀▀▄▄ ▒█▀▀█ ▒█▀▀▀ ▒█▄▄▀ 
   ▒█░░░ ▒█░▒█ ▄█▄ ▒█▄▄▄█ ▒█░▒█ ▒█▄▄▄ ▒█░▒█\n                                            ${yellow}v1.0${green}\n"
printf "${red}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
printf "   ${yellow}.:H a c k e r  C o l o n y  O f f i c i a l:.\n"
printf "${red}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n" 
printf "    ${cyan}A Basic Phishing Tool BY Hacker colony offcial\n\n\n"

}

function configure() {
rm -rf $BIN/hcophish  ${file} &> /dev/null
printf "\e[0m\n"
printf "\e[0m\n"
	echo -e "\n${GREEN}[${WHITE}+${GREEN}]${CYAN} Installing required packages..."
sleep 4
    if [[ -d "/data/data/com.termux/files/home" ]]; then
        if [[ `command -v proot` ]]; then
            printf ''
        else
			echo -e "\n${GREEN}[${WHITE}+${GREEN}]${CYAN} Installing package : ${ORANGE}proot${CYAN}"${WHITE}
            pkg install proot resolv-conf -y
        fi

        if [[ `command -v tput` ]]; then
            printf ''
        else
			echo -e "\n${GREEN}[${WHITE}+${GREEN}]${CYAN} Installing package : ${ORANGE}ncurses-utils${CYAN}"${WHITE}
            pkg install ncurses-utils -y
        fi

    fi

if [[ `command -v php` && `command -v wget` && `command -v curl` && `command -v 7z` ]]; then
		echo -e "\n${GREEN}[${WHITE}+${GREEN}]${GREEN} Packages already installed."
else
		pkgs=(php curl wget p7zip p7zip-full)
		for pkg in "${pkgs[@]}"; do
			type -p "$pkg" &>/dev/null || {
				echo -e "\n${GREEN}[${WHITE}+${GREEN}]${CYAN} Installing package : ${ORANGE}$pkg${CYAN}"${WHITE}
				if [[ `command -v pkg` ]]; then
					pkg install "$pkg" -y
				elif [[ `command -v apt` ]]; then
					apt install "$pkg" -y
				elif [[ `command -v apt-get` ]]; then
					apt-get install "$pkg" -y
				else
					echo -e "\n${RED}[${WHITE}!${RED}]${RED} Unsupported package manager, Install packages manually."
					{ exit 1; }
				fi
			}
		done
fi
printf "\e[0m\n"
printf "\e[0m\e[1;91m[\e[0m\e[1;97m~\e[0m\e[1;91m]\e[0m\e[1;93m Creating Environment...\e[0m\n"
printf "\e[0m\n"
sleep 4
chmod +x HCO-Phisher; mv HCO-Phisher $BIN/hcophish
7z x tempfile
#rm tempfile
cd ..
mv HCO-Phisher ${file}
sleep 2
printf "\e[0m\n"
printf "\033[1;32m[✔] Installation Succeed !! \e[0m\n"
#\e[0m\e[1;91m[\e[0m\e[1;97m~\e[0m\e[1;91m]
sleep 2
printf "\e[0m\n"
printf "\e[0m\n"
printf "\e[0m\e[1;91m[\e[0m\e[1;97m~\e[0m\e[1;91m]\e[0m\e[1;93m Type \e[0m\e[1;92mhcophish \e[0m\e[1;93mto run\e[0m\n"
printf "\e[0m\n"
printf "\e[0m\n"
}
os
banner
configure

